### ISSUE TITLE
生成序列化文件失败

### ISSUE THREAD

**Issue by XuCcc** [wh1t3p1g/ysomap#17]
```bash
ysomap payload(CommonsBeanutils1) bullet(ProcessBuilderBullet) > run
[+] generate payload(CommonsBeanutils1) started!
[+] generate payload(CommonsBeanutils1) done!
[+] generate CommonsBeanutils1 success, plz see obj.ser
java.io.NotSerializableException: java.lang.ProcessBuilder
        at java.io.ObjectOutputStream.writeObject0(Unknown Source)
        at java.io.ObjectOutputStream.writeObject(Unknown Source)
        at java.util.PriorityQueue.writeObject(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
        at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
        at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
        at java.io.ObjectOutputStream.writeObject0(Unknown Source)
        at java.io.ObjectOutputStream.writeObject(Unknown Source)
        at ysomap.core.serializer.DefaultSerializer.serialize(DefaultSerializer.java:25)
        at ysomap.core.serializer.SerializerFactory.serialize(SerializerFactory.java:52)
        at ysomap.cli.Session.run(Session.java:213)
        at ysomap.cli.Console.dispatch(Console.java:127)
        at ysomap.cli.Console.run(Console.java:77)
        at ysomap.cli.App.main(App.java:17)
ysomap payload(CommonsBeanutils1) bullet(ProcessBuilderBullet) > show options
```

**Comment by wh1t3p1g** [comment]
你好，对于不同类型的payload，bullet是不能随便选的。ysomap会提示哪些bullet是可选的，比如cb1
![image](https://user-images.githubusercontent.com/16203770/123032200-23ceef80-d418-11eb-91af-a0c79171824f.png)
仅可选TemplatesImplBullet
